# GitVote configuration file

audit:
  enabled: false

# Default profile → invoked with /vote
profiles:
  default:
    # Enforce policies described in our governance file, see: https://github.com/microcks/.github/blob/main/GOVERNANCE.md
    duration: 2w
    pass_threshold: 66
    # Check vote status every day, default is fine for us here
    periodic_status_check: "1 day"
    # Let's automate the issue or PR closing when the vote is done 👍
    close_on_passing: true
    # This allows participants sufficient opportunity to engage
    # and reflect before the vote is automatically finalized; 1 week for community feedback and comments
    close_on_passing_min_wait: "1 week"
    # Currently, and according to our governance file, only maintainers have the right to vote
    # You are still encouraged to participate in voting, even if your vote is not binding, ref: close_on_passing_min_wait option above
    # Note: allowed_voters, we are not using the team maintainers to exclude microcks-bot
    allowed_voters:
      users:
        - lbroudoux
        - yada
        - SebastienDegodez
      exclude_team_maintainers: false
  
  # Steering Committee profile → invoked with /vote-sc
  sc:
    duration: 2w
    pass_threshold: 66
    periodic_status_check: "1 day"
    close_on_passing: true
    close_on_passing_min_wait: "1 week"
    allowed_voters:
      teams:
        - steering-committee
      exclude_team_maintainers: false
